using VRArcadeFinder.Models.DTOs;
using VRArcadeFinder.Models.Domain;

namespace VRArcadeFinder.Tests.Models
{
    public class ArcadeSearchResultDtoTests
    {
        [Theory]
        [InlineData(500, "500m")]
        [InlineData(999, "999m")]
        [InlineData(1000, "1.0km")]
        [InlineData(2500, "2.5km")]
        [InlineData(10000, "10.0km")]
        public void DistanceDisplay_FormatsCorrectly(double distance, string expected)
        {
            var dto = new ArcadeSearchResultDto { Distance = distance };
            Assert.Equal(expected, dto.DistanceDisplay);
        }

        [Fact]
        public void RatingDisplay_ShowsRating_WhenPresent()
        {
            var dto = new ArcadeSearchResultDto { AverageRating = 4.5m };
            Assert.Contains("4.5", dto.RatingDisplay);
        }

        [Fact]
        public void RatingDisplay_ShowsNoRatings_WhenNull()
        {
            var dto = new ArcadeSearchResultDto { AverageRating = null };
            Assert.Equal("No ratings", dto.RatingDisplay);
        }

        [Fact]
        public void DefaultValues_AreCorrect()
        {
            var dto = new ArcadeSearchResultDto();

            Assert.Equal(string.Empty, dto.Name);
            Assert.Equal(string.Empty, dto.Address);
            Assert.Equal(string.Empty, dto.City);
            Assert.Equal(string.Empty, dto.Slug);
            Assert.Empty(dto.LatestReviews);
        }
    }

    public class CityModelTests
    {
        [Fact]
        public void City_HasCorrectDefaults()
        {
            var city = new City();

            Assert.True(city.IsEnabled);
            Assert.True(city.IsActive); // alias
            Assert.False(city.IsPriority);
            Assert.Equal(0, city.CrawlCount);
            Assert.Equal(0, city.ArcadeCount);
            Assert.Equal(15, city.MaxResults);
            Assert.Equal(50000, city.SearchRadius);
            Assert.Equal("US", city.Region);
        }

        [Fact]
        public void City_IsActive_AliasesIsEnabled()
        {
            var city = new City();

            city.IsActive = false;
            Assert.False(city.IsEnabled);

            city.IsEnabled = true;
            Assert.True(city.IsActive);
        }

        [Fact]
        public void City_IdAlias_Works()
        {
            var city = new City { CityId = 55 };
            Assert.Equal(55, city.Id);
        }
    }

    public class CrawlHistoryModelTests
    {
        [Fact]
        public void CrawlHistory_HasCorrectDefaults()
        {
            var history = new CrawlHistory();

            Assert.Equal("InProgress", history.Status);
            Assert.Equal(0, history.ArcadesFound);
            Assert.Equal(0, history.ArcadesAdded);
            Assert.Equal(0, history.ArcadesUpdated);
        }

        [Fact]
        public void CrawlHistory_Aliases_Work()
        {
            var history = new CrawlHistory
            {
                CrawlHistoryId = 33,
                ArcadesFound = 10,
                ArcadesAdded = 5
            };

            Assert.Equal(33, history.Id);
            Assert.Equal(10, history.TotalFound);
            Assert.Equal(5, history.NewArcades);
        }
    }

    public class BlogPostModelTests
    {
        [Fact]
        public void BlogPost_HasCorrectDefaults()
        {
            var post = new BlogPost();

            Assert.False(post.IsPublished);
            Assert.False(post.IsAutoGenerated);
            Assert.Equal(0, post.ViewCount);
            Assert.Equal(string.Empty, post.Title);
            Assert.Equal(string.Empty, post.Content);
        }

        [Fact]
        public void BlogPost_AuthorName_AliasesAuthor()
        {
            var post = new BlogPost { Author = "Test Author" };
            Assert.Equal("Test Author", post.AuthorName);
        }
    }

    public class CrawlSettingsTests
    {
        [Fact]
        public void CrawlSettings_HasCorrectDefaults()
        {
            var settings = new VRArcadeFinder.Models.CrawlSettings();

            Assert.True(settings.EnableAutoCrawl);
            Assert.Equal(3, settings.CitiesPerBatch);
            Assert.Equal(2, settings.RetryDelayHours);
            Assert.Equal(30, settings.DelayBetweenCitiesSeconds);
            Assert.Equal(15, settings.MaxResultsPerCity);
            Assert.Equal(30, settings.CheckIntervalMinutes);
        }
    }
}
