using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BoardGameCafeFinder.Models.Domain
{
    public class BlogPost
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(300)]
        public string Title { get; set; } = string.Empty;

        [Required]
        [MaxLength(300)]
        public string Slug { get; set; } = string.Empty;

        [MaxLength(500)]
        public string? Summary { get; set; }

        [Required]
        public string Content { get; set; } = string.Empty;

        [MaxLength(500)]
        public string? FeaturedImage { get; set; }

        [MaxLength(100)]
        public string? Category { get; set; }

        [MaxLength(500)]
        public string? Tags { get; set; } // Comma-separated tags

        // SEO
        [MaxLength(200)]
        public string? MetaTitle { get; set; }

        [MaxLength(300)]
        public string? MetaDescription { get; set; }

        // Author
        [MaxLength(100)]
        public string? Author { get; set; }

        // Status
        public bool IsPublished { get; set; } = false;
        public bool IsAutoGenerated { get; set; } = false;

        // Related data for auto-generated posts
        [MaxLength(100)]
        public string? RelatedCity { get; set; }

        [MaxLength(100)]
        public string? RelatedCountry { get; set; }

        public string? PostType { get; set; } // "top-games", "city-guide", "custom", etc.

        // Timestamps
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
        public DateTime? PublishedAt { get; set; }

        // Stats
        public int ViewCount { get; set; } = 0;
    }
}
